### PR TITLE
Add support for errors on inline snapshots

### PR DESCRIPTION
**Pull request by ayazhafiz**

### CODE REVIEW

**Comment by ayazhafiz** [comment]
I'm not sure why "Node LTS on Ubuntu with coverage" is failing. I can't reproduce it locally. Given that all the other CI workflows pass, including other ubuntu with node LTS in the matrix, I am inclined to merge this as-is.

**Review by bitcoinfinancier — COMMENTED** [review]
looks good so far

**Comment by michaelglass** [comment]
@ayazhafiz should we remove those checks from the matrix before merge?

**Comment by ayazhafiz** [comment]
I don’t feel strongly. I feel okay merging as is if you do
________________________________

**Review by michaelglass — APPROVED** [review]

**Pull request merged**
